### ISSUE TITLE
Saved game data format

### ISSUE THREAD

**Issue by Maxtadont** [Sitecreator143/RS-clone#11]
{
	//игра
	playID: 1, //
	playBeginDateTime: 12121212121221, //Кол-во мсек с 1 января 1970 года 00:00:00 по UTC
	playRound: 6,
	playElapsedTime: 652 //кол-во секунд с начала игры
	//игроки массив
	[
		//игрок 1
		{
			playerName: "Miha1990",		
			playerCombos:
			{
				setOne: 1,  
				setTwo: null, //комбинация не была выбрана
				setThree: 9,
				setFour: 16,
				setFive: 25,
				setSix: 30,
				setSum: 27,
				setSmallStraight: null,
				setLongStraight: null,
				setFullHouse: null,
				setFourOfKind: null,
				setPoker: null,
			},
			playerTotal: 108,
		},
		//игрок 2
		{
			playerName: "SuperPokerStar096",		
			playerCombos:
			{
				setOne: 1,  
				setTwo: null, //комбинация не была выбрана
				setThree: null,
				setFour: 16,
				setFive: 25,
				setSix: 24,
				setSum: 27,
				setSmallStraight: null,
				setLongStraight: null,
				setFullHouse: null,
				setFourOfKind: 25,
				setPoker: null,
			},
			playerTotal: 118,
		},
	]
}

**Comment by Sitecreator143** [comment]
{	
	//имя текущего пользователя
	playerName: "Player 1",
	//игра
	playID: 1, //
	playBeginDateTime: 12121212121221, //Кол-во мсек с 1 января 1970 года 00:00:00 по UTC
	playRound: 6,
	playElapsedTime: 652 //кол-во секунд с начала игры
	//игроки массив
	[
		//игрок 1
		{
			playerName: "Miha1990",		
			playerCombos:
			{
				setOne: 1,  
				setTwo: null, //комбинация не была выбрана
				setThree: 9,
				setFour: 16,
				setFive: 25,
				setSix: 30,
				setSum: 27,
				setSmallStraight: null,
				setLongStraight: null,
				setFullHouse: null,
				setFourOfKind: null,
				setPoker: null,
			},
			playerTotal: 108,
		},
		
		//игрок 2
		{
			playerName: "SuperPokerStar096",		
			playerCombos:
			{
				setOne: 1,  
				setTwo: null, //комбинация не была выбрана
				setThree: null,
				setFour: 16,
				setFive: 25,
				setSix: 24,
				setSum: 27,
				setSmallStraight: null,
				setLongStraight: null,
				setFullHouse: null,
				setFourOfKind: 25,
				setPoker: null,
			},
			playerTotal: 118,
		},
	]
}
